name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cc
      run: sudo sh -c 'echo "deb http://us.archive.ubuntu.com/ubuntu trusty main universe" >> /etc/apt/sources.list'
    - name: configure
      run: sudo apt-get update
    - name: configure1  
      run: sudo apt-get install mingw32 mingw32-binutils mingw32-runtime
    - name: corr
      run: whereis i686-w64-mingw32-gcc
 
