name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get update
    - name: configure1  
      run: sudo apt-get install mingw32-gcc
    - name: corr
      run: ./cross-compile-mingw.sh
 
